### ISSUE TITLE
Can't get css-in-js-mode work on Emacs 29.1

### ISSUE THREAD

**Issue by llemaitre19** [orzechowskid/tree-sitter-css-in-js#29]
Hi @orzechowskid !

Thanks for sharing grammar and minor Emacs mode for css in js.

Sadly,  after installing `css-in-js-mode` in Emacs and the grammar, it seems not to work. I get no error, but css in js is not highlighted nor indended.

A bit debugging leads me to notice that `treesit-range-settings` is not set correctly (as far I know), as it values is `((css-in-js-mode--treesit-set-ranges nil nil))`.

I have tried both of `main` and `emacs-29` branches. I am using `Emacs 29.1`, but according to this [issue](https://github.com/orzechowskid/tree-sitter-css-in-js/issues/21), `css-in-js-mode` is compatible, isn't it ?

Thanks for your help !

**Comment by orzechowskid** [comment]
hello, and thank you for the kind words.

this emacs minor mode should indeed be compatible with emacs 29.1 but it seems that treesit has changed a bit since the last time I used this library.  it may take me a little while to fix these issues but I do think I know how to do it.

**Comment by llemaitre19** [comment]
Thanks for your reply, I am waiting for news then. 👍️

**Comment by orzechowskid** [comment]
hi!  please try the `bugfix/29` branch to see if your experience is improved.  (it's not 100% finished yet but I believe I've made a lot of progress.)

**Comment by llemaitre19** [comment]
Nice, thank you very much. A quick test confirms that it works really better ! Indentation, syntax highlighting and completion seem now to work.

I  will check deeper as soon as possible to give you a more detailed feedback.

**Comment by llemaitre19** [comment]
I have tested a little more, all work great excepted these few points:
- syntax highlighting of css properties is not the same compared to `css-ts-mode`, is it the expected behaviour ?
- if the closing backquote is on its own line, its indentation is the same as the content (should be decreased by one level, I believe)
- comment function (`comment-dwim`) seems not to be customized in css region (`//` instead of `/* */`)

If it can help, I can make a PR for the last point.

**Comment by orzechowskid** [comment]
this has been merged into `main` branch.  thanks!
